<?php
include '../includes/constants.php';
include '../includes/header.php';
include '../includes/nav.php';
?>


<div class="link">
<h2>There is Too Much Evil and Suffering For God to Exist?</h2>
by Rich Deem

<h3>Introduction</h3>
Purpose of Evil?
    Most atheists assume that a personal God would only create a universe that is both good morally and perfect physically. However, according to Christianity, the purpose of the universe is not to be morally or physically perfect, but to provide a place where spiritual creatures can choose to love or reject God - to live with Him forever in a new, perfect universe, or reject Him and live apart from Him for eternity. It would not be possible to make this choice in a universe in which all moral choices are restricted to only good choices. One cannot choose between good and bad if bad did not exist. It's an amazing simple logical principle.

Rich Deem
Atheists often claim that the presence of evil is an argument against the existence of God. The Christian God is supposed to be both loving and all-powerful. Despite these characteristics, God seems to be unable or unwilling to prevent the vast amount of evil and suffering in the world. The atheist concludes that either God is not loving or not all-powerful or that God does not exist, because if He did exist, He could stop all the suffering. The atheistic arguments contain some subtle assumptions that, as I will show, do not apply to the God of the Bible and His created universe. Even the assumption that evil and suffering are bad for us must be questioned in light of what the Bible says. This page specifically defends the principle that moral evil must exist. Another page examines the reasons why natural evil must exist. Although many atheists claim the presence of moral evil precludes the existence of God, others admit that God would be completely justified in allowing moral evil.1

<h3>The atheists' logical argument</h3>
What I have found is that atheists like to say that their arguments against God's existence specifically exclude the God of the Bible as a God who could exist. However, in reality, atheists produce generic arguments against a generic God whose characteristics and creation do not match those that are described in the Bible. Atheists may not accept what the Bible says, but they cannot say the God of the Bible cannot logically exist and then ignore what the Bible has to say about the characteristics of God. If the atheist states that the God of the Bible is logically impossible, he cannot pick and choose which arguments from the Bible to accept in order to "prove" his point. Let's formalize the atheist's arguments:

God is all-powerful, loving, and perfect.
A perfect, loving God would create a universe that was perfect (e.g., no evil and suffering).
The universe is not perfect but contains evil and suffering.

Therefore, God does not exist.
<h3>The Bible's Response</h3>
The Bible does state that God is "all powerful." In the Old Testament, one of God's titles is "El Shadday," which is translated "God Almighty."2 The Bible also states that God is loving.3 In fact, the Bible indicates that God is love.4 The Bible also indicates that God is perfect.5 So, we can agree that the first statement is a correct interpretation of what the Bible says about the characteristics of God.

The next statement indicates that a perfect, loving God must create a universe that is perfect. This is the statement that is false and invalidates the argument. Nowhere does the Bible state that the universe was created to be perfect. God Himself called it "good"6 and "very good,"7 but never "perfect." In fact, God Himself stated that part of the original creation was "not good."8 The Bible states that the current universe is not perfect,9 but was designed to be temporary10 and will be replaced with a perfect universe11 that will be permanent.12 Science also tells us that the universe was designed to be temporary.13

Why two creations instead of one?
Why would God create an imperfect, temporary universe only to replace it later with a perfect one? Why wouldn't God have created a perfect universe in the first place? This is a good question, but shows a lack of understanding of the biblical reason of why God created the universe. One can find the reason for the creation of the universe in the first few chapters of the Bible. God created humans in order to have a personal relationship with them, which He had with Adam and Eve before they sinned (Genesis 2). Jesus said that the first and foremost commandment was to "Love the Lord your God..."14 A personal relationship, characterized by the possibility of love, is only possible if created beings are given free will. If God had created the universe with no possibility of evil or sin, then the created beings would have had no free will, and, as such, would essentially be programmed computers. Such beings would be incapable of love, since love involves making a choice - which requires the ability to choose not to love. For example, I can program my computer to say "I love you" when it starts up. Does this mean that the computer really loves me? Of course not! Likewise, God could have programmed humans to say that they loved Him, without the possibility of rejecting Him or performing evil deeds. However, these programmed beings would exhibit about as much true love as my computer - not a very satisfying relationship. Therefore, God created the universe for the express purpose of allowing free will spiritual beings the opportunity to have fellowship with Him (and likewise, reject Him).

<h3>What does God want?</h3>
God's purposes in creating the universe go beyond merely creating free will beings that love Him in this temporary universe. Jesus explained the ultimate goal of God in the parable of the banquet:

Jesus replied: "A certain man [representing God] was preparing a great banquet and invited many guests. At the time of the banquet he sent his servant to tell those who had been invited, 'Come, for everything is now ready.' But they all alike began to make excuses. The first said, 'I have just bought a field, and I must go and see it. Please excuse me.' Another said, 'I have just bought five yoke of oxen, and I'm on my way to try them out. Please excuse me.' Still another said, 'I just got married, so I can't come.' The servant came back and reported this to his master. Then the owner of the house became angry and ordered his servant, 'Go out quickly into the streets and alleys of the town and bring in the poor, the crippled, the blind and the lame.' 'Sir,' the servant said, 'what you ordered has been done, but there is still room.' Then the master told his servant, 'Go out to the roads and country lanes and make them come in, so that my house will be full. (Luke 14:16-23)

This parable tells that God wants not only a relationship with humans in this universe, but a relationship with billions15 of these creatures in His future, perfect creation. If God's purpose is to have relationships with free will beings in a future creation, then there must be a means by which these beings can make a choice to enter or not enter into this relationship. The means by which we make this choice is exactly the message of the Bible.

Therefore. the Bible says that God allows temporary, bounded evil16 in order to allow free will beings to have the ability to love and to make choices. I am going to propose something which seems to support the atheists' arguments regarding evil. I agree that there is a lot of evil in the world. In fact, there is too much evil in the world from what would be expected from chaos theory or the laws of physics. Evolution does not explain the vast amount of evil done by mankind. None of the other creatures on our planet have the capacity for evil that mankind have. No other mammals kill arbitrarily. They only kill to eat and survive - but not mankind. Just watch the nightly news or read your newspaper. Look at all the evil perpetuated in the last century alone - 6 million Jews killed by Hitler, 40 million Russians killed by Stalin, 2 million Cambodians killed by their own government in the 1970's. In fact, the Pol Pot regime specifically preached atheism and sought to exterminate all religious expression in Cambodia. In addition to these atrocities, there have been hundreds of massacres committed in virtually every nation of the world. The Bible says that the presence of evil is due to the spiritual component of our nature - something that animals do not possess. God endowed His spiritual creatures (humans and angels) with free will to love God or to oppose Him. The most powerful created being (the angel Satan) rebelled and led one third of the angels into opposition against God. Those humans who oppose or ignore God follow Satan into rebellion - either consciously or unconsciously. Some people blame the evil on "society." However, society is composed of individuals who make individual choices. Most of the evil is committed by people who oppose the will of society. In contrast, there are many examples of societies in the animal kingdom, especially among the primates. None of these societies have the capacity for evil that we have. We are different from all other animals on our planet - a fact that has no scientific or evolutionary explanation.17

Why pain is necessary
The atheist also makes the assumption that all pain, suffering, and death are bad or evil. In fact, physical pain is absolutely vital to our survival. If we felt no pain, we would do things to ourselves that could be very destructive.18 For example, if we didn't feel pain when we touched a hot object, we would not react until we saw our flesh smoking. This is obviously not a good thing to do. Pain tells us we need to react to a situation before serious damage occurs.

Evil as a means of spiritual growth
Many things that people consider to be bad are, in fact, useful in our spiritual growth. The Bible says that trials in our lives produce perseverance, which helps make us mature and complete.19 These trials also increase our faith - a "refining by fire."20 The Bible tells us that "all things to work together for good to those who love God."21 Let me give you a couple concrete examples in my own life that illustrate these points.

I got very sick in 1985, at which time the tests revealed I had Crohn's disease, a serious, incurable inflammatory disease of the intestines. I found myself unable to do things using my own abilities and strength. I was bedridden in severe pain for two months, with the medicine doing nothing to improve my condition. I considered that I would probably spend the rest of my life in pain, in and out of hospitals. Not being able to do anything else in my own strength, I cried out to God and promised to try to follow Him and do what He wanted me to do (although I had no idea what that was at the time). Within three months all symptoms of Crohn's disease had disappeared. The trial was awful at the time, but God had to break my will, so that, when I heard the gospel of Jesus Christ three years later, I accepted it and turned my life over to Jesus, which has been the greatest joy of my life. In addition, I am much more thankful for my good health since that time of trial, and have been more sympathetic and helpful to others who are undergoing similar trials.

In 1996 my wife Carole and I learned that she had an inoperable brain tumor, and was expected to live four to seven years. We had been married only seven years and had three sons, aged 5, 3 and 1 years old at the time. The time since then has been difficult, but it has produced some remarkable changes in Carole. Her interest in jewelry, clothes, and other unimportant things has been replaced by a heightened commitment to family, and raising our boys. She also is more committed to helping others and regularly offers help as she is able. In addition, during this time God has been faithful in answering our prayers and comforting us through the many people who have loved us. What has been abundantly clear is that those people who have gone through the most severe trials are the ones who have ministered most to us. The trials these people have experienced have made them sensitive to the needs of others in similar situations, in ways that only they can understand. I know through this trial God will make me a better ambassador of Jesus Christ, and bring me opportunities for ministry which I would have ignored, had I not gone through this experience. In talking to other Christians about sufferings, you will find that it is through trials that they grow in their character and their faith. During the "easy" times, we become complacent. For the non-Christian, he sees the trials as mere annoyance or pointless suffering, often resulting in bitterness.

<h3>Conclusion Top of page</h3>


God did not design this universe to be perfect, but as a temporary creation where free will beings make choices about where they want to spend eternity (in the new creation, which will be perfect).
The new creation will be perfect, but will not have absolute free will for its inhabitants. We must agree in this life to give up some of our free will in the next life. Those who are unwilling to give up their own free will choices will not be forced to do so in the next life. However, they will have to be separated from the new creation, since God is unwilling to compromise His character.
All people will suffer at least somewhat because of bad choices that others make. In addition, because of the temporary nature of the universe, some bad things will happen to us due to "bad luck" or chance. However, these things will teach us to be more sensitive to the needs of others, and will prepare us to show God's love to others when they suffer through similar things. God want us to learn from this life, not just have a party.
</div>

<?php include '../includes/footer.php';?>
