<?php
include '../includes/constants.php';
include '../includes/header.php';
include '../includes/nav.php';
?>




<div class="link">
Are miracles really possible?

I’m not talking about how some describe a baby being born as “the miracle of life.” I’m talking about biblical reports of Jesus walking on water, healing the blind, and physically rising from the dead. Atheists sometimes say miracles overturn the laws of nature—and that’s not possible. Before considering the evidence, however, many skeptics have already decided that naturalism is true. But what about this? Do miracles—by definition—really overturn the laws of nature?

In the foreword to The God Conversation, Lee Strobel notes how J.P. Moreland responded to this challenge with a simple defense (p.7):

The laws of nature are the way we describe how the world usually works. If someone drops an apple, it falls to the floor. That’s gravity.

However, if someone were to drop an apple and I were to reach over and grab it before it hit the ground, I wouldn’t be overturning the law of gravity. I would simply be intervening. In a similar way, God is able to reach into the world that he created by performing a miracle. He isn’t contravening or overturning the laws of nature. He’s simply intervening.

Of the almost four thousand religions around the world, none can boast more than thirty-two percent of the world’s population. [i] The lack of consensus does not always come from disagreement over morals or distaste for the main message of the religion. Oftentimes people reject religions because they do not believe certain claims those religions make. These claims are most often miraculous claims, and they are the heart and center of many religions. If they are true, the religion they belong to must be considered. If they are false, then the core of a religion is based on lies.

Everyday usage of the term ‘miracle’ varies, so let us begin with the working definition of a miracle—an event that is an exception to the ordinary course of nature. Note that this definition excludes the use of the term ‘miracle’ in circumstances that are extraordinary but completely possible within the laws of nature. If, for example, a person were dealt a royal flush (the odds of which are 1 in 649,739), the hand would be a happy coincidence, not a miracle. A miracle would be a phenomenon such as the sun stopping in the sky or water transforming into wine.

Miracles such as these can be considered impossible or possible. If they are considered possible, this does not validate all miraculous claims ever made for any religion; the evidence for and against each individual supernatural event must be weighed. In this article, I will argue that miracles are possible, but I will not discuss which specific miracles are in fact probable. I will begin by looking at some foundational arguments against miracles. I will then reject these arguments using the defense of several apologists. Finally, I will address additional common problems with the way individuals look at miracles.

In his 1748 essay, “Of Miracles,” David Hume provided the foundation for the vast majority of modern anti-miracle arguments that he claimed would “be an everlasting check to all kinds of superstitious delusion.” [ii] Hume’s argument was threefold. He first said, “A miracle is a violation of the laws of nature; and as firm and unalterable experience has established these laws, the proof against a miracle, from the very nature of the fact, is as entire as any argument from experience can possibly be imagined.” [iii] According to this statement, the proof for a miracle can never overcome the proof against it. Second, Hume discussed the tendency of miracles to occur in developing nations and in ancient times. The reason for this, according to Hume, was the difference in people’s tendency to believe miracles. People from earlier times were more prone to accept miracles without much disbelief or resistance.

Finally, Hume used an analogy of testimony in court. When one testimony conflicts another, they are both invalidated. In Hume’s words:

Every miracle, therefore, pretended to have been wrought in any of these religions (and all of them abound in miracles), as its direct scope is to establish the particular system to which it is attributed; so has it the same force, though more indirectly, to overthrow every other system. In destroying a rival system, it likewise destroys the credit of those miracles, on which that system was established; so that all the prodigies of different religions are to be regarded as contrary facts, and the evidences of these prodigies, whether weak or strong, as opposite to each other. [iv]
Hume concluded that the Christian religion is based upon miracles and cannot be believed rationally or scientifically.

Antony Flew, a British philosopher of the twentieth century, praised the ideas behind Hume’s arguments but criticized its details, fine tuning it to solidify what Hume argued. He first defined miracles as anything that occurs outside the laws of nature. Flew then examined the possibility of many Christians’ claim that miracles do not have to defy natural laws. He argued that miracles that are within the natural order of things do not serve as any proof for the existence of a higher being, and so the miracles are essentially meaningless.

To develop his argument, Flew quoted Cardinal Newman, an apologist whom he called “Hume’s most worthy opponent.” [v] Cardinal Newman challenged the application of Hume’s argument to “these particular miracles, ascribed to the particular Peter, James, and John” and that the question to consider is if miracles are:

unlikely supposing there is a power, external to the world, who can bring them about, supposing they are the only means by which He can reveal himself to those who need a revelation; supposing that He is likely to reveal himself, that He has a great end in doing so. [vi]
Flew responded that even if God exists, we do not have the capability of grasping his intentions and it is therefore not possible to assume things about God.

Before turning to various Christian apologists’ responses to these arguments, let us define ‘miracle’ in a more precise way. Richard Purtill, a professor of philosophy at Western Washington University, defines a miracle as “an event brought about by the power of God that is a temporary exception to the ordinary course of nature for the purpose of showing that God has acted in history.” [vii] Purtill notes that this does not create any conflict between science and religion, stating that, “Of course, by defining miracles as exceptions to the natural order of things, we deprive miracles of any scientific interest only if science is essentially concerned with what happens as part of the natural order of things…since exceptions brought about by personal agency cannot be predicted from a study of what normally happens.” [viii]

There are several problems with Hume and Flew’s arguments, as addressed directly by acclaimed apologist Norman Geisler. First, let us consider Hume’s first argument in his own words. Geisler summarized:

“A miracle is a violation of the laws of nature.”
“Firm and unalterable experience has established these laws.”
“A wise man…proportions his belief to the evidence.”
Therefore, “the proof against a miracle… is as entire as any argument from experience can possibly be imagined.” [ix]
The problem with this argument lies in the second premise. By saying that “unalterable experience has established these laws,” Hume begged the question by already assuming that miracles have never occurred. If they had, then the evidence against them would not be “firm and unalterable.” If Hume meant to say that most of the evidence lies against miracles, then he would have avoided this question-begging. The problem with this, however, is that it sums evidence rather than weighing evidence. Because miracles are in themselves a rare occurrence, they will always have a smaller amount of evidence, but each piece of evidence has differing value. It makes sense, then, to at least first consider the value of the evidence for miracles, and then to consider the value of the evidence against them. Contemplate this non-miraculous example quoted by Francis Beckwith:

Life magazine once reported that all 15 people scheduled to attend a rehearsal of a church choir in Beatrice Neb., were late for practice on March 1, 1950, and each had a difference reason: a car wouldn’t start, a radio program wasn’t over, ironing wasn’t finished, a conversation dragged on. It was fortunate that none arrived on schedule at 7:15 pm – the church was destroyed by an explosion at 7:25. The choir members wondered whether their mutual delays were an act of God…[It was] estimated there was a one-in-a-million chance that all 15 would be late the same evening. [x]
Although this (non-miraculous) circumstance has an obvious amount of odds against it, it actually occurred.

By the arguments of Hume and Flew, it should be discounted because the amount of evidence against this sort of event is numerous due to its high improbability, and the evidence for it can never outnumber the evidence against. The relevant comparison, however, is not the amount, but the weight of evidence for the testimony.

The report from Life magazine was affirmed by reliable testimonies, and so even though its likelihood was slim, a reasonable person should conclude the report’s truth. Additionally, there are plenty of events the truth of which occurrences we do not challenge despite the fact that they are naturalistically unrepeatable and thus have a large summed total of evidence against them. For example, the fact that the Big Bang has never been repeated cannot and should not be used as an argument against its likelihood. It is therefore better to weigh evidence rather than add evidence, or else we would have no belief in even the origin of life being an actual event.

Stephen Davis, a prominent writer on Christian philosophy, addressed Hume’s second argument that miracles occurred in places and time periods where they could not easily be proven wrong. While intuitively attractive, this idea is factually incorrect. Spirits, miracles, demons, and angels were not commonplace in history; they were always extraordinary and recounted in detail with disbelief. The way miracles were received throughout history is actually not very different than the responses to miraculous claims nowadays; they resulted in numerous writings and responses, varying from disbelief to radical life transformations. [xi]

Hume’s third argument concluded that miraculous claims from opposing religions conflict and therefore negate each other. As said previously, if miracles are possible, this does not mean that all miracles are probable. If every miracle ever recorded for any religion were true, then these miracles would directly contradict each other because the religions in themselves contradict (and this was Hume’s point). His fault was that he assumed that if miracles were possible, all miracles become probable. In reality, when the evidence for certain miracles far outweighs others, these miracles are deemed false.

Let us now return to Flew’s point that no one can guess the motivations and desires of God. David Beck, a professor of philosophy at Liberty University, concluded that we can know a little about God using three arguments that are adequate to prove the likelihood of God acting directly in history through miracles. Oftentimes, miracles are used to argue for the existence of God. Many people have a problem with this, seeing miracles as impossible or not completely proven. Although Beck personally believes there is plentiful evidence behind miracles, he argued that one can arrive at God’s existence without referring to miracles. Then, assuming the existence of God, Beck argued that one can prove the possibility of miracles if this God is:

Powerful enough to produce events in space/time
An intelligence with a capacity to frame the convergence of events in space/time
A personality with a moral concern to act in history.xii
David Beck used the cosmological argument to support premise one, the teleological argument to support premise two, and the moral argument to support premise three. [xiii] While a thorough explanation of these specific arguments is outside the scope of this paper, one can certainly see how the truth of the three premises allows for the possibility of miracles; a God with a moral concern to act in history who has the power and intelligence to do so is certainly capable of performing miracles, making them possible.

No matter how powerfully presented the argument is for miracles, it cannot stand against a solidified worldview that denies their possibility. Every human being has a conceptual framework, which is the lens through which they see the world. This worldview can distort truth and create biases, so we must address the paradigms to see the effects they have on one’s view of miracles. “A conceptual framework is the pattern or arrangement of our concepts (ideas) that enables us to make sense of the world by organizing all that we believe.” [xiv] Purtill made the case that these conceptions of natural laws can change the possibility of miracles. If one assumes a theistic position, miracles are entirely possible. This view contains the ideas that natural laws were set into place by a creator to order the world, and so it follows that this creator is the only one who can violate these laws. On the other hand, the metaphysical naturalist conception assures that everything exists within natural laws. This view makes miracles impossible by the very idea that nothing can violate these natural laws.

While a thorough defense of theism is outside of the scope of this article, let us quickly consider some of the arguments for theism and against naturalism. Arguing for theism, Richard Purtil stated:

The theistic scientist has a philosophical reason for expecting laws to be discovered in nature: he thinks that such laws are the product of a mind, namely, the mind of God. The non-theistic scientist, however, can have no such assurances. For him the fact that nature functions in lawlike fashion is ultimately a ‘brute fact,’ completely unexplainable on his own views. [xv]
So, perhaps it is a bit more advantageous to a complete understanding of these natural laws if a higher power is assumed. Richard Taylor, a philosopher concerned with metaphysics, added to this argument by showing that if natural laws were simply “brute facts,” they could not be trusted to give factual information. He used an analogy: Suppose you are on a railway and look out the window. There are rocks on the hillside that spell out “the British Railways Welcome You to Wales.” Seeing this, you deduct two possible ways these rocks could have come to this arrangement. Either someone put them there, or the rocks randomly fell into place. If someone put them there, it is logical to suppose you are actually headed into Wales. If the rocks randomly fell into place, however, it is illogical to assume that you are actually headed into Wales; therefore you cannot extract any meaning out of them. [xvi] A premeditated arrangement of rocks is analogous to the theistic worldview. Because theism believes the world was created, it can deduce meaning out of this world. However, metaphysical naturalism illustrates the world coming about by chance alone, and then tries to ascertain meaning within the world. Take human senses. Is it not illogical to believe these came about by chance, but that they somehow offer valuable information that is true and reasonable? Believing this is the same as believing the rocks on the hillside were a chance event yet still offering true information.

Ronald Nash, a professor for over forty years of theology, apologetics, and ethics, introduced one of the fundamental problems with metaphysical naturalism. It assumes that the universe began randomly without a purpose or has always been existent because a “creation” would necessitate a higher power or something larger than or outside of the universe. Human reasoning, however, poses a problem for this conception of a self-explanatory universe. For example, we can use reasoning to deduce that “if it is true that all man are mortal and if it is true that Socrates is a man, then it must be true that Socrates is mortal.” [xvii] So “by definition, metaphysical naturalism excludes the possible existence of anything beyond nature, anything outside the box. But, the process of reasoning requires something that exceeds the bounds of nature, namely, the laws of logical inference.” [xviii]

Thus, the opposing view to theistic science has its setbacks, and so theistic science should not be so easily discarded. Theism, unlike methodological naturalism and the complementary view, can fully account for the ultimate beginning of the universe.

A person’s metaphysical perspective plays an influential role in determining whether miracles are possible. A theistic worldview has many advantages over metaphysical naturalism. With the theistic mindset, miracles are possible. The arguments proposed by Hume and Flew, while well thought out and worthy of consideration, should not be blindly accepted in light of viable counterarguments. Without certain evidence against miracles, and with a valid theistic mindset, miracles are possible in our history, in our present, and in our future.

</div>
<?php include '../includes/footer.php';?>
